### ISSUE TITLE
Make AppStateStatus a enum and export it

### ISSUE THREAD

**Issue by arthurgeron-work** [react-native-community/hooks#211]
`AppStateStatus`   should be a enum and export, it's better for stability, using with the useAppState hook and avoids having to manually create enums for app states which could potentially change in the future leading to more issues.

If this is accepted I can create a PR for it.

**Comment by LinusU** [comment]
~Is there a specific reason that you want an enum over a type union? Since there is no concept of enum's in plain javascript they have some implications that one need to think about in order to make every use case work good.~

~I'd be open to a PR right now that just fixes the return type to a union~

Just saw that there is already a type for this exported from the React Native typings, could you send a PR to use that one? It's already imported in the file even, so should be a one-liner!

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d076add9f29db350a19bd94c37b197729cc02f87/types/react-native/index.d.ts#L7349

**Comment by arthurgeron** [comment]
Thank you for endorsing this change @LinusU , I've created a PR.
