### ISSUE TITLE
Can't use Hook useDimensions

### ISSUE THREAD

**Issue by swarnava-bhattacharya** [react-native-community/hooks#331]
I see many people on YouTube tutorials using this specific hook but I can't import it, did y'all remove it by any chance? And if so how can I replicate the same thing with a different hook?

**Comment by LinusU** [comment]
It this what you are looking for? 

https://reactnative.dev/docs/usewindowdimensions

**Comment by SammyGutierrez335** [comment]
To answer the original question. Yes they did on pr 322.
https://github.com/react-native-community/hooks/pull/322

The tutorial I am working is using @react-native-community/hooks v2.5.1. 
Run `npm install @react-native-community/hooks@2.5.1` if you want to go through your tutorials using the similar code. However, it likely is wise to just find the updated way of getting the same result.

**Comment by anmol242** [comment]
I am not sure why this was removed but `useWindowDimesions` is not stable. I have opened new issue for tracking what is the reason behind it: https://github.com/react-native-community/hooks/issues/390

See the thread related to Dimensions API in RN. Thread seems to close due to inactivity but Dimension API is not stable. I was  using that in one of my application and when I open alert on same screen. Dimension listener sends delay response due to which UI disturbs in application.
Thread for issue: https://github.com/facebook/react-native/issues/29451
